@host=http://localhost:5000

### Upload Image
POST {{host}}/api/actors/
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="Untitled.png"
Content-Type: image/png

< ./Untitled.png
--boundary123--